server:
  port: 8080

spring:
  application:
    name: case-ingestion-service

camel:
  springboot:
    name: CaseIngestionCamel
  component:
    kafka:
      brokers: localhost:9092

logging:
  level:
    com.police: DEBUG
    org.apache.camel: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics